import { defineField, defineType } from "sanity";

export default defineType({
  name: 'author',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: rule =>
        rule.required().error('Name is required'),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      description: `
        A slug is an unique value for a author,
        used to route to the correct author when navigating the website.
        It is generated by using the name of the author and making it URL-friendly.
      `,
      options: {
        source: 'name'
      },
      validation: rule =>
        rule.required().error('Slug is required'),
    }),
    defineField({
      name: 'image',
      title: 'Image',
      type: 'image',
      options: {
        hotspot: true,
      },
      fields: [
        defineField({
          name: 'alt',
          title: 'Alternative text',
          description: `
            Alternative text is read by the users screen reader. It's important that
            the text describes what is on the image.
          `,
          type: 'string',
          validation: rule =>
            rule.required().warning(
              "For accessibility reasons alternative text is needed"
            )
        }),
        defineField({
          name: 'caption',
          title: 'Caption',
          type: 'string',
        })
      ]
    }),
    defineField({
      name: 'bio',
      type: 'blockContent',
    }),
  ],
  preview: {
    select: {
      title: 'name',
      media: 'image'
    }
  }
})
